server:
  port: 9096

eureka:
  instance:
    hostname: userApplication
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
    server:
      wait-time-in-ms-when-sync-empty: 3000
      enableSelfPreservation: false

consultaServer:
  ribbon:
    eureka:
      enabled: false
    listOfServers: consultaServer:9091,consultaServer:9092
    ServerListRefreshInterval: 15000
