server:
  port: 9096

eureka:
  instance:
    hostname: userapplication
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
    server:
      wait-time-in-ms-when-sync-empty: 3000
      enableSelfPreservation: false

consultaServer:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
