 server:
  port: 9096

 eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
      enableSelfPreservation: false

 dojo-consulta-server:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:9093,localhost:9094,localhost:9095
    ServerListRefreshInterval: 15000